Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using test.Data;
using test.Models;

namespace test.Pages
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> _logger;
        private readonly BaseDbContext _dbContext;

        public CreateModel(ILogger<CreateModel> logger, BaseDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        [BindProperty]
        public SoOrderDetailDto OrderDetail { get; set; }

        public List<ComCustomer> Customers { get; set; } = [];

        public async Task OnGet()
        {
            Customers = await _dbContext.ComCustomers.ToListAsync();
        }

        public async Task OnPost()
        {
            var soOrder = new SoOrder()
            {
                ComCustomerId = OrderDetail.CustomerId,
                OrderDate = DateTime.Parse(OrderDetail.OrderDate.ToString()),
                Address = OrderDetail.Address,
                OrderNo = OrderDetail.SalesOrder,
            };

            await _dbContext.SoOrders.AddAsync(soOrder);

            await _dbContext.SaveChangesAsync();

            foreach (var item in OrderDetail.Items)
            {
                await _dbContext.SoItems.AddAsync(new()
                {
                    SoOrderId = soOrder.SoOrderId,
                    ItemName = item.ItemName,
                    Price = item.Price,
                    Quantity = item.Qty,
                });

                await _dbContext.SaveChangesAsync();
            }
        }
    }
}

Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Mysqlx.Crud;
using Org.BouncyCastle.Asn1.X509;
using test.Data;
using test.Models;

namespace test.Pages
{
    public class EditModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly BaseDbContext _dbContext;

        public EditModel(ILogger<IndexModel> logger, BaseDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        [BindProperty]
        public SoOrderDetailDto OrderDetail { get; set; }

        [BindProperty]
        public List<ComCustomer> Customers { get; set; }


        public async Task OnGet(long id)
        {

            Customers = await _dbContext.ComCustomers.ToListAsync();

            var order = await _dbContext.SoOrders.Include(i => i.SoItems).Include(i => i.ComCustomer).Where(x => x.SoOrderId == id).FirstOrDefaultAsync();

            var items = new List<SoItemDto>();

            foreach (var item in order.SoItems)
            {
                items.Add(new()
                {
                    ItemName = item.ItemName,
                    Price = item.Price,
                    Qty = item.Quantity,
                    Total = item.Price * item.Quantity
                });
            }


            OrderDetail = new()
            {
                ID = id,
                OrderDate = DateOnly.FromDateTime(order.OrderDate),
                Customer = order.ComCustomer.CustomerName,
                CustomerId = order.ComCustomerId,
                SalesOrder = order.OrderNo,
                Address = order.Address,
                Items = items
            };

        }

        public async Task<IActionResult> OnPost()
        {
            var order = await _dbContext.SoOrders
                .Include(i => i.SoItems)
                .Include(i => i.ComCustomer)
                .Where(x => x.SoOrderId == OrderDetail.ID)
                .FirstOrDefaultAsync();

            order.OrderNo = OrderDetail.SalesOrder;
            order.Address = OrderDetail.Address;
            order.ComCustomerId = OrderDetail.CustomerId;
            order.OrderDate = DateTime.Parse(OrderDetail.OrderDate.ToString());

            _dbContext.Update(order); 

            _dbContext.SoItems.RemoveRange(order.SoItems);

            foreach (var item in OrderDetail.Items)
            {
                _dbContext.SoItems.Add(new SoItem
                {
                    ItemName = item.ItemName,
                    Price = item.Price,
                    Quantity = item.Qty,
                    SoOrderId = order.SoOrderId
                });
            }

            await _dbContext.SaveChangesAsync();

            return RedirectToPage();
        }

    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace test.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using test.Data;
using test.Models;

namespace test.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly BaseDbContext _dbContext;

    [BindProperty]
    public List<SoOrderDto> Orders { get; set; } = [];
    public int TotalPage { get; set; } = 0;
    public int TotalItem { get; set; } = 0;
    public int CurrentPage { get; set; } = 1;

    public IndexModel(ILogger<IndexModel> logger, BaseDbContext dbContext)
    {
        _logger = logger;
        _dbContext = dbContext;
    }

    public async Task OnGetAsync([FromQuery] string? keyword, [FromQuery] DateTime? orderDate, [FromQuery] int pages = 1, [FromQuery] int perPage = 5)
    {

        CurrentPage = pages <= 1 ? 1 : pages * perPage;

        IQueryable<SoOrder> query = _dbContext.SoOrders.Include(x => x.ComCustomer).OrderByDescending(x => x.OrderDate);

        TotalItem = await query.CountAsync();

        if (keyword != null) query = query.Where(x => x.OrderNo.Contains(keyword));
        if (orderDate != null) query = query.Where(x => x.OrderDate.Date == orderDate);

        var list = await query.Skip((pages - 1) * perPage).Take(perPage).ToListAsync();

        var count = await query.CountAsync();

        TotalPage = count >= perPage ? count / perPage : 1;

        foreach (var item in list)
        {
            Orders.Add(new SoOrderDto()
            {
                ID = item.SoOrderId,
                OrderDate = DateOnly.FromDateTime(item.OrderDate),
                SalesOrder = item.OrderNo,
                Customer = item.ComCustomer.CustomerName,
                CustomerId = item.ComCustomer.ComCustomerId
            });
        }
    }

    public async Task<IActionResult> OnPostDelete(int id)
    {
        var order = await _dbContext.SoOrders.Where(x => x.SoOrderId == id).FirstOrDefaultAsync();
        _dbContext.SoOrders.Remove(order);
        await _dbContext.SaveChangesAsync();

        return RedirectToPage();
    }

    public async Task<IActionResult> OnGetExport()
    {

        var orders = await _dbContext.SoOrders.Include(x => x.ComCustomer).OrderByDescending(x => x.OrderDate).ToListAsync();
        using (var workbook = new XLWorkbook())
        {
            var worksheet = workbook.Worksheets.Add("Items");
            var currentRow = 1;

            // Header
            worksheet.Cell(currentRow, 1).Value = "ID";
            worksheet.Cell(currentRow, 2).Value = "Sales Order";
            worksheet.Cell(currentRow, 3).Value = "Order Date";
            worksheet.Cell(currentRow, 4).Value = "Customer";
            worksheet.Cell(currentRow, 5).Value = "Address";

            // Isi data
            foreach (var order in orders)
            {
                currentRow++;
                worksheet.Cell(currentRow, 1).Value = order.SoOrderId;
                worksheet.Cell(currentRow, 2).Value = order.OrderNo;
                worksheet.Cell(currentRow, 3).Value = order.OrderDate.ToString("dd-MM-yyyy");
                worksheet.Cell(currentRow, 4).Value = order.ComCustomer.CustomerName;
                worksheet.Cell(currentRow, 5).Value = order.Address;
            }

            using (var stream = new MemoryStream())
            {
                workbook.SaveAs(stream);
                var content = stream.ToArray();

                return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"Orders-{DateTime.Now.ToString("dd-MM-yyyy")}.xlsx");
            }
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace test.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Create.cshtml
@page
@model CreateModel
@{
    ViewData["Title"] = "Item";
}

@section NavbarTitle {
    <a class="navbar-brand text-white ms-3" style="font-size: 25px; font-weight: bold;" asp-area="" asp-page="/Index">
        ADD NEW - SALES ORDER
    </a>
}

<form method="post">

    <div class="pt-3 pb-3" style="background-color:#082c5c">
        <h3 class="text-center text-white">Sales Order Information</h3>
    </div>

    <div class="p-3 mb-3 container-fluid">
        <div class="row">
            <div class="col-md-6 mb-3">
                <div class="row">
                    <div class="col-6">
                        <label for="salesOrderNumber">Sales Order Number *</label>
                    </div>
                    <div class="col-6">
                        <input type="text" id="salesOrderNumber" class="form-control" placeholder="Input Here" asp-for="@Model.OrderDetail.SalesOrder">
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div class="row">
                    <div class="col-6">
                        <label for="customer">Customer</label>
                    </div>
                    <div class="col-6">
                        <select id="customer" class="form-control" asp-for="@Model.OrderDetail.CustomerId">
                            <option>Select One</option>
                            @foreach (var customer in Model.Customers)
                            {
                                <option value="@customer.ComCustomerId">@customer.CustomerName</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <div class="row">
                    <div class="col-6">
                        <label for="orderDate">Order Date *</label>
                    </div>
                    <div class="col-6">
                        <input type="date" id="orderDate" class="form-control" asp-for="@Model.OrderDetail.OrderDate">
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div class="row">
                    <div class="col-6">
                        <label for="address">Address</label>
                    </div>
                    <div class="col-6">
                        <input type="text" id="address" class="form-control" placeholder="Input Here" asp-for="@Model.OrderDetail.Address">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="pt-3 pb-3 mb-3" style="background-color:#082c5c">
        <h3 class="text-center text-white">Detail Item Information</h3>
    </div>

    <div class="p-3 mb-3 container-fluid">

        <button type="button" onclick="addRow()" class="btn btn-danger mb-3">Add Item</button>

        <table class="table table-bordered table-striped">
            <thead class="table-dark">
                <tr>
                    <th>No</th>
                    <th>Action</th>
                    <th>Item Name</th>
                    <th>Qty</th>
                    <th>Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody id="table-item"></tbody>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <div class="row mt-3">
                            <div class="col-md-12 text-end">
                                <strong>Total Item:</strong> <span id="total-items">0</span>
                                <strong>Total Amount:</strong> <span id="total-amount">0.00</span>
                            </div>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>

    </div>

    <div class="text-center container-fluid">
        <button type="submit" class="btn btn-danger">Save</button>
        <a asp-page="Index" class="btn btn-secondary">Close</a>
    </div>

</form>

<style>
    .container {
        max-width: 1200px;
        margin: auto;
    }

    .table-dark {
        background-color: #003366;
        color: #fff;
    }
</style>

@section Scripts {
    <script>
        let no = 1;
        let index = 0;

        function addRow() {
            const table = document.getElementById("table-item");
            const item = document.createElement('tr');

            item.id = `item-table-${index}`;

            item.innerHTML = `
                 <td>${no}</td>
                 <td class="text-center justify-content-center align-items-center">
                    <button onclick="saveRow(${index})" type="button"  id="save-btn-${index}" class="btn btn-dark btn-sm"><i class="bi bi-save"></i></button>
                    <button type="button" onclick="editRow(${index})" id="edit-btn-${index}" class="btn btn-warning btn-sm" hidden><i class="bi bi-pencil"></i></button>
                 </td>
                 <td><input id="item-${index}" name="OrderDetail.Items[${index}].ItemName" class="form-control" /></td>
                 <td><input type="number" oninput="updateTotal(${index})" id="qty-${index}" name="OrderDetail.Items[${index}].Qty" class="form-control" /></td>
                 <td><input type="number" oninput="updateTotal(${index})" id="price-${index}" name="OrderDetail.Items[${index}].Price" class="form-control" /></td>
                 <td id="total-${index}">0.00</td>
            `;
            table.appendChild(item);

            no++;
            index++;
            calculateSummary();
        }

        function removeRow(index) {
            const element = document.getElementById(`item-table-${index}`);
            element.remove();
            calculateSummary();
            no--;
        }

        function saveRow(index) {
            const item = document.getElementById(`item-${index}`);
            const qty = document.getElementById(`qty-${index}`);
            const price = document.getElementById(`price-${index}`);
            const edit =  document.getElementById(`edit-btn-${index}`);
            const save =  document.getElementById(`save-btn-${index}`);

            if (qty.value && price.value && item.value) {
                item.disabled = true;
                qty.disabled = true;
                price.disabled = true;
                edit.hidden = false;
                save.hidden = true;
            }
        }

        function editRow(index) {
            const item = document.getElementById(`item-${index}`);
            const qty = document.getElementById(`qty-${index}`);
            const price = document.getElementById(`price-${index}`);
            const edit =  document.getElementById(`edit-btn-${index}`);
            const save =  document.getElementById(`save-btn-${index}`);

            item.disabled = false;
            qty.disabled = false;
            price.disabled = false;
            edit.hidden = true;
            save.hidden = false;
        }

        function updateTotal(index) {
            const qty = document.getElementById(`qty-${index}`);
            const price = document.getElementById(`price-${index}`);
            const total = document.getElementById(`total-${index}`);
            total.innerHTML = formatNumber((qty.value || 0) * (price.value || 0));
            calculateSummary();
        }

        function calculateSummary() {
            const rows = document.querySelectorAll("#table-item tr");
            let totalItems = 0;
            let totalAmount = 0;

            rows.forEach(row => {
                const qtyInput = row.querySelector('input[name*="Qty"]');
                const priceInput = row.querySelector('input[name*="Price"]');
                if (qtyInput && priceInput) {
                    const qty = parseFloat(qtyInput.value) || 0;
                    const price = parseFloat(priceInput.value) || 0;
                    totalItems += qty;
                    totalAmount += qty * price;
                }
            });

            document.getElementById("total-items").textContent = totalItems;
            document.getElementById("total-amount").textContent = formatNumber(totalAmount);
        }
        calculateSummary();
    </script>
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@section NavbarTitle {
    <a class="navbar-brand text-white ms-3" style="font-size: 25px; font-weight: bold;" asp-area="" asp-page="/Index">
        SALES ORDER
    </a>
}

<div class="container-fluid">
    <form class="border border-dark border rounded-4 mb-3">
        <div class="row mb-3 mt-3 ps-3 pe-3">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-6">
                        <label for="keywords">Keywords</label>
                    </div>
                    <div class="col-6">
                        <input type="text" id="keywords" name="keyword" class="form-control" placeholder="Input Here">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-6">
                        <label for="order-date">Order Date</label>
                    </div>
                    <div class="col-6">
                        <input type="date" id="order-date" name="orderDate" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary mb-3 me-3">Search</button>
        </div>
    </form>

    <div class="d-flex justify-content-between mb-3">
        <div>
            <a asp-page="Create" class="btn btn-danger">Add New Data</a>
            <a asp-page-handler="Export" class="btn btn-success"><i class="bi bi-file-earmark-excel"></i>Export To Excel</a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead class="table-dark">
            <tr>
                <th>No</th>
                <th>Action</th>
                <th>Sales Order</th>
                <th>Order Date</th>
                <th>Customer</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Orders.Count; i++)
            {
                <tr>
                    <td>@(i + 1)</td>
                    <td class="align-items-center justify-content-center text-center">
                        <form class="align-items-center justify-content-center text-center" method="post" asp-page-handler="Delete" asp-route-id="@Model.Orders[i].ID" onsubmit="return confirm('Are you sure?')">
                            <a asp-page="Edit" asp-route-id="@Model.Orders[i].ID" class="btn btn-warning btn-sm"><i class="bi bi-pencil"></i></a>
                            <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></button>
                        </form>
                    </td>
                    <td>@Model.Orders[i].SalesOrder</td>
                    <td>@Model.Orders[i].OrderDate.ToString("dd/MM/yyyy")</td>
                    <td>@Model.Orders[i].Customer</td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5">
                    <nav class="navbar">
                        <ul class="pagination">
                            <li class="page-item">
                                <a class="page-link" aria-label="Previous" asp-page="Index" asp-route-pages="@(Model.CurrentPage > 1 ? Model.CurrentPage - 1 : 1)" asp-route-perpage="5">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            @for (int i = 1; i <= Model.TotalPage; i++)
                            {
                                <li class="page-item"><a class="page-link" asp-page="Index" asp-route-pages="@i" asp-route-perpage="5">@i</a></li>
                            }
                            <li class="page-item">
                                <a class="page-link"aria-label="Next" asp-page="Index" asp-route-pages="@(Model.CurrentPage/5+1)" asp-route-perpage="5">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul>

                        <strong id="text-pagination" class="text-secondary">@Model.CurrentPage - @(Model.CurrentPage + 4) of @Model.TotalItem items</strong>
                    </nav>
                </td>
            </tr>
        </tfoot>
    </table>

    
</div>

<style>
    .container {
        max-width: 1200px;
        margin: auto;
    }

    .table-dark {
        background-color: #003366;
        color: #fff;
    }
</style>